name: example
description: &#x27;A new Flutter project. Created by Slidy&#x27;
homepage: https://github.com/RodolfoBonis/DayCalendar/tree/master/example
version: 1.0.0+1
environment:
  sdk: '>=2.2.2 <3.0.0'
dependencies:
  day_calendar_flutter:
    path: ../
  intl: ^0.17.0
  flutter_mobx: ^1.0.1
  mobx: ^1.0.2+2
  flutter_modular: ^3.0.2+1
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
dependency_overrides:
  intl: ^0.17.0
dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.2
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
scripts:
  watch: flutter pub run build_runner watch --delete-conflicting-outputs --use-polling-watcher